#!/usr/bin/env python

import sys
from math import *

import rospy
from sensor_msgs.msg import JointState

global duration_hold

def joint_pub():
	global duration_hold

	rospy.init_node('talker', anonymous=True)

	pub_js = rospy.Publisher('/mantis_uav/command/joints', JointState, queue_size=10)

	duration_hold = rospy.Duration(float(sys.argv[1]))
	update_rate = rospy.Rate(50)

	update_rate.sleep()

	config_j1 = [0.0, 0.0, 0.75, 0.75, 0.0]
	config_j2 = [0.0, 0.75, 0.0, 0.75, 0.0]
	assert len(config_j1) == len(config_j2), "Joint config lists are not equal"
	num_configs = len(config_j1)
	configs = [config_j1, config_j2]

	i = 0
	done = False
	moved_time = rospy.Time.now()

	js = JointState()
	js.header.frame_id = "mantis_uav"
	js.name = ["joint_shoulder", "joint_elbow"]

	while((not done) and not rospy.is_shutdown()):
		js.header.stamp = rospy.Time.now()
		js.position = [configs[0][i], configs[1][i]]
		pub_js.publish(js)

		if(rospy.Time.now() > (moved_time + duration_hold)):
			rospy.loginfo("Finished hold on config %i" % i)
			i = i + 1
			moved_time = rospy.Time.now()

		if(i >= num_configs):
			done = True

		update_rate.sleep()

if __name__ == '__main__':
	try:
		joint_pub()
	except rospy.ROSInterruptException:
		pass
