#!/usr/bin/env python

import sys
from math import *

import rospy
from std_msgs.msg import Float64

global duration_hold

def joint_pub():
	global duration_hold

	rospy.init_node('talker', anonymous=True)

	pub_j1 = rospy.Publisher('/mantis_uav/joint_position_controller/joint_shoulder/command', Float64, queue_size=10)
	pub_j2 = rospy.Publisher('/mantis_uav/joint_position_controller/joint_elbow/command', Float64, queue_size=10)

	duration_hold = rospy.Duration(float(sys.argv[1]))
	update_rate = rospy.Rate(50)

	update_rate.sleep()

	config_j1 = [0.0, 0.785398163, 0.785398163, 1.57079632679, 0.0]
	config_j2 = [0.0, 0.0, 0.785398163, 0.0, 0.0]
	assert len(config_j1) == len(config_j2), "Joint config lists are not equal"
	num_configs = len(config_j1)
	configs = [config_j1, config_j2]

	i = 0
	done = False
	moved_time = rospy.Time.now()

	while(not done):
		pub_j1.publish(configs[0][i])
		pub_j2.publish(configs[1][i])

		if(rospy.Time.now() > (moved_time + duration_hold)):
			i = i + 1
			moved_time = rospy.Time.now()

		if(i >= num_configs):
			done = True

		update_rate.sleep()

if __name__ == '__main__':
	try:
		joint_pub()
	except rospy.ROSInterruptException:
		pass
