#!/usr/bin/env python

import sys
from math import *

import rospy
from sensor_msgs.msg import JointState

def joint_pub():
	global duration_hold

	rospy.init_node('fake_joint_state', anonymous=True)

	pub_js = rospy.Publisher('/mantis_uav/state/joints', JointState, queue_size=10)

	update_rate = rospy.Rate(20)

	js = JointState()
	js.header.frame_id = "mantis_uav"
	js.name = ["joint_shoulder", "joint_elbow"]
	js.position = [0.0, 0.0]
	js.velocity = [0.0, 0.0]
	js.effort = [0.0, 0.0]

	while(not rospy.is_shutdown()):
		js.header.stamp = rospy.Time.now()
		pub_js.publish(js)

		update_rate.sleep()

if __name__ == '__main__':
	try:
		joint_pub()
	except rospy.ROSInterruptException:
		pass
