function [ t, s ] = gen_spline( t_vias, vias, order, dt )
%GEN_DATA_POINT_STRUCT Summary of this function goes here
%   Detailed explanation goes here

    % Full trajectory times
    t0 = t_vias(1);
    tf = t_vias(end);
    
    % Pre-allocate vectors
    t = t0:dt:tf;
    s = zeros(5,length(t));

    % Itterate over the list of vias in pairs
    si = 1;
    for i = 2:size(vias,2)
        % Segment times
        st0 = t_vias(i-1);
        stf = t_vias(i);
        sn = (stf-st0) / dt; % Number of points for this segment of spline
        
        %st = linspace(st0, stf, sn);
        switch(order)
            case 3
               [~, sq] = spline_solver_cubic(sn+1, ...
                                              st0, ...
                                              stf, ...
                                              vias(1,i-1), ...
                                              vias(2,i-1), ...
                                              vias(1,i), ...
                                              vias(2,i));
            case 5
                [~, sq] = spline_solver_quintic(sn+1, ...
                                                 st0, ...
                                                 stf, ...
                                                 vias(1,i-1), ...
                                                 vias(2,i-1), ...
                                                 vias(3,i-1), ...
                                                 vias(1,i), ...
                                                 vias(2,i), ...
                                                 vias(3,i));
            case 7
                [~, sq] = spline_solver_septic(sn+1, ...
                                                st0, ...
                                                stf, ...
                                                vias(1,i-1), ...
                                                vias(2,i-1), ...
                                                vias(3,i-1), ...
                                                vias(4,i-1), ...
                                                vias(1,i), ...
                                                vias(2,i), ...
                                                vias(3,i), ...
                                                vias(4,i));
            case 9
                [~, sq] = spline_solver_nonic(sn+1, ...
                                               st0, ...
                                               stf, ...
                                               vias(1,i-1), ...
                                               vias(2,i-1), ...
                                               vias(3,i-1), ...
                                               vias(4,i-1), ...
                                               vias(5,i-1), ...
                                               vias(1,i), ...
                                               vias(2,i), ...
                                               vias(3,i), ...
                                               vias(4,i), ...
                                               vias(5,i));
            otherwise
                error('Unknown spline order')
        end
        
        s(:,si:(si+sn-1)) = sq(:,1:end-1);
        si = si+sn;
    end

    % Fill in the final data point
    s(:,end) = vias(:,end);
end

