#!/usr/bin/env python
import rospy
from visualization_msgs.msg import Marker

if __name__ == "__main__":
	rospy.init_node("bends_pipe")
	pub = rospy.Publisher("/mantis_uav/env/pipe", Marker, queue_size=10, latch=True)

	msg_out = Marker()
	msg_out.header.frame_id = "map"
	msg_out.header.stamp = rospy.Time.now()

	msg_out.ns = "mantis_env"
	msg_out.id = 0
	msg_out.type = Marker.CYLINDER
	msg_out.action = Marker.ADD
	msg_out.lifetime = rospy.Time(0)
	msg_out.frame_locked = True

	# Place the marker at [1.0,1.0,0.0]
	# with no rotation
	msg_out.pose.position.x = 0.0
	msg_out.pose.position.y = 0.5
	msg_out.pose.position.z = 1.0
	msg_out.pose.orientation.w = 0.7071
	msg_out.pose.orientation.x = 0.0
	msg_out.pose.orientation.y = 0.7071
	msg_out.pose.orientation.z = 0.0

	# Make a square tile marker with
	# size 0.1x0.1m square and 0.02m high
	msg_out.scale.x = 0.9
	msg_out.scale.y = 0.9
	msg_out.scale.z = 10.0

	# Make the tile a nice opaque blue
	msg_out.color.r = 0.2
	msg_out.color.g = 0.5
	msg_out.color.b = 0.8
	msg_out.color.a = 1.0

	# Publish the marker
	pub.publish(msg_out)

	try:
		rospy.spin()
	except rospy.ROSInterrupyException:
		pass
