#!/usr/bin/env python2

import sys
from math import *

import roslib
roslib.load_manifest('mantis_planner')
import rospy
import actionlib

from mantis_planner.movement_dispatcher import DispatcherFull

if __name__ == '__main__':
	rospy.init_node('dispatcher_full')
	server = DispatcherFull()

	rospy.loginfo("Loaded plan dispatcher")

	try:
		rospy.spin()
	except rospy.ROSInterruptException:
		pass
