#!/usr/bin/env python

import sys

from rqt_mantis_commander.commander import MantisCommander
from rqt_gui.main import Main

plugin = 'rqt_mantis_commander'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
