#!/usr/bin/env python

import sys

from mantis_rqt_eyedropper.m_eyedrop import MEyedrop
from rqt_gui.main import Main

plugin = 'mantis_rqt_eyedropper'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
